### PR TITLE
Feature-gate composite key doctests, so we can enable them for `cargo test --no-default-features`

### PR DESCRIPTION
**Pull request by pitaj**
The only other way is to use `#[cfg_attr(feature = "map", doc = "..."]` everywhere. I thought this was a better solution.

### CODE REVIEW

**Comment by udoprog** [comment]
Hm. I'll be merging #23 before this.

But I've been considering how to run doctests nicely with specific features included or not-included. My approach so far has been to use no-std and composite keys which do not depend on `map` as much as possible with new doctests (e.g. `bool` and `Option<bool>`). Then we could move all the doc tests related to `&'static str` and numerical types into the module where `MapStorage` lives which should follow somewhat natural from how the features are organized.

As for the README, since it's a limited number of tests feature gating the relevant parts is probably better. I'm also not entirely keen on the workflow where the `README.md` is included and prefer running [`cargo-readme`](https://github.com/livioribeiro/cargo-readme) as appropriate. But maybe I can change my mind. It might be nice to not have to deal with synchronizing the two.

**Comment by udoprog** [comment]
I've rebased your change and modified it. I kept your commit around this time to make sure you have something to reference in case you want to discuss it.

The changes I did was:

Not including the readme as a string. I'm not entirely comfortable with it as part of my workflow yet and I encountered some editor weirdness that I'd like to resolve before doing it. But thanks for the suggestion!

I've switched to using a `bool` composite key for existing tests. The goal of having most tests as doctests is so that they can function as dual use with testing functionality while providing documentation. Having them live in a separate module will probably just mean nobody notices them and they might as well be separate tests.

I'm using detailed feature testing in `lib.rs`, this is (correctly) stripped by `cargo readme`.

**Comment by pitaj** [comment]
Hey it looks like you added back the "Unsafe Usage" section of the readme again. Did you mean to?

Additionally, I imagine some of these doctests were adding coverage - we may want to add them back as regular unit tests somewhere or as doctests for MapStorage.

**Comment by udoprog** [comment]
Yeah, rebase got a bit weirded out. The unsafe section was removed later on again!

As for `MapStorage`. Not a ton of coverage missing to be fair. Most of it is just pass-through now to hashbrown. Option and singleton storage might need some more love though.

**Pull request merged**
