### PR TITLE
Intersection api for Set

### PR DESCRIPTION
**Pull request by RoDmitry**
(copy from HashSet)

### CODE REVIEW

**Comment by RoDmitry** [comment]
Any links that explain why `::core` is inconsistent?

**Comment by udoprog** [comment]
> Any links that explain why `::core` is inconsistent?

It was an inconsistent across my own projects and doesn't contribute to how the code is compiled. It can sometimes be useful inside of macros if there's ambiguity.

Also, thanks for the impl!

The build was disabled due to Github policy so I was never pinged when it was completed. Since I needed to push again to re-trigger the build I decided to do a bit of cleanup at the same time.

**Comment by udoprog** [comment]
There are some more [HashSet APIs](https://doc.rust-lang.org/std/collections/struct.HashSet.html) that could be ported if that's something you want to take a stab at. I added the `From<[T; N]> impl for Set<T>` here which allows doc tests to be a bit cleaner. Otherwise I'll be baking a new release in a day or two.

The primary issue for "missing APIs" is #11.

**Comment by RoDmitry** [comment]
Not important, but I personally prefer `::core` and `::std` so it compiles a bit faster, like milliseconds faster, maybe which nobody would even notice 🙂

**Pull request merged**
